name: 'GitHub Server Stats Prometheus Exporter'
description: 'Exports GitHub Server Stats to a Prometheus Pushgateway'
inputs:
  personal-access-token:  
    description: 'The PAT to use to access the REST API for the server stats'
    required: true
  enterprise-or-organization:  
    description: 'Enterprise or Organization slug'
    required: true
  prometheus-pushgateway-url:
    description: 'The URL of a Prometheus Pushgateway to send the metrics to'
    required: true
runs:
  using: 'node16'
  main: 'index.js'