name: Export Server Stats

on:
  workflow_dispatch:
  
  schedule:
  # runs 2x an hour, 17th and 37th minute
    - cron:  '17/30 * * * *'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: bxtp4p/github-server-stats-prom-exporter@main
        with:
          personal-access-token: ${{ secrets.ACCESS_TOKEN }}
          enterprise-or-organization: ${{ secrets.ENTERPRISE_NAME }}
          prometheus-pushgateway-url: ${{ secrets.PROM_PUSHGATEWAY_URL }}
